project:
  type: website
  output-dir: docs

website:
  title: "SMUA4500 - Smart Cities"
  description: "Course website for SMUA4500 - Smart Cities at Oslo Metropolitan University"
  navbar:
    search: true
    background: "#FFDC00"
  search:
    location: navbar
    type: overlay
  sidebar:
    logo: "images/mini-Logo_OsloMet.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/gregmaya/oslomet-smua4500
        text: GitHub
    style: docked
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      # Main weekly expansion happening here
      - section: Schedule
        href: src/index.qmd
        contents: 
          - section: "Unit 3"
            contents:
              - text: System Thinking
                href: src/unit_3/1_system_thinking.qmd
              - text : Bibliography
                href: src/unit_3/references.qmd
              #- text: Decision Support
              #  href: src/unit_3/2_decision_support.qmd
              #- text: Data Visualization
              #  href: src/unit_3/data_viz.qmd

      - href: resources.qmd
        text : "Additional Resources"
  page-footer:
    center:
      - text: "Content released under CC0 1.0 Universal"
        href: LICENSE  # or "LICENSE.html" or the CC0 URL


format:
  html:
    theme: default
    css: styles.css
    mainfont: "Moderat, Arial"
    toc: true
    favicon: /images/favicon.ico

execute:
  freeze: auto

