project:
  type: website
  output-dir: docs

website:
  title: "SMUA4500 - Smart Cities"
  description: "Course website for SMUA4500 - Smart Cities at Oslo Metropolitan University"
  navbar:
    search: true
    background: "#FFDC00"
  search:
    location: navbar
    type: overlay
  sidebar:
    logo: "images/mini-Logo_OsloMet.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/gregmaya/oslomet-smua4500
        text: GitHub
    style: docked
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      # Main weekly expansion happening here
      - section: Schedule
        href: src/index.qmd
        contents: 
          - href: src/week2.qmd
            text : "Week 2"
          - href: src/week3.qmd
            text : "Week 3"
      - href: data/index.qmd
        text: Datasets
      - href: resources.qmd
        text : "Additional Resources"
      - href: https://github.com/gregmaya/oslomet-smua4500/discussions
        text: Forum
  page-footer:
    center:
      - text: "Content released under CC0 1.0 Universal"
        href: LICENSE  # or "LICENSE.html" or the CC0 URL

favicon: "images/oslomet-favicon.png"

format:
  html:
    theme: default
    css: styles.css
    mainfont: "Moderat, Arial"
    toc: true

execute:
  freeze: auto

