[project]
name = "oslomet-smua4500"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.1",
    "ipykernel>=7.1.0",
    "jupyterlab>=4.5.1",
]
